apiVersion: v1
kind: Pod
metadata:
  name: sleepybox1
  labels:
    name: sleepybox1
    access: "true"
spec:
  containers:
  - name: sleepybox
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]

---

apiVersion: v1
kind: Pod
metadata:
  name: sleepybox2
  labels:
    name: sleepybox2
    access: "false"
spec:
  containers:
  - name: sleepybox
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]